#!/usr/bin/env python3
# License: 5G-MAG Public License (v1.0)
# Authors: Jordi J. Gimenez (5G-MAG)
# Copyright: (C) 2026 5G-MAG Association
#
# For full license terms please see the LICENSE file distributed with this
# program. If this file is missing then the license can be retrieved from
# https://www.5g-mag.com/license

"""Generate the rt-media-origin configuration for the demo from channels.json.

One `live` channel per entry: rt-media-origin loops the channel's source file from CONTENT_ROOT
with its own ffmpeg process, packages it as live DASH (H.264 video and AAC audio for television,
AAC audio only for radio, with rt-media-origin's audioOnly channels) and serves it at
/<stream>/manifest.mpd, the URL the service list generated by write-service-list.py points at.
Both generators read the same channels.json, honour the same DEMO_CHANNELS filter, and build the
path from the same `stream` field, so the origin and the service list cannot disagree about where
a channel is.

The file is written into the demo's own run/ directory, never into the rt-media-origin checkout,
and every channel's output.dir is a directory under run/origin/ as well. That matters:
rt-media-origin empties a channel's output.dir each time it starts the channel.

Usage:
  write-origin-config.py            write ORIGIN_CONFIG
  write-origin-config.py --dry-run  print the configuration, write nothing

Reads CHANNELS_FILE, CONTENT_ROOT, MEDIA_HOST, MEDIA_PORT, LIVE_SEG_DURATION, LIVE_WINDOW,
LIVE_EXTRA_WINDOW, LIVE_VIDEO_BITRATE, ORIGIN_CONFIG and ORIGIN_OUTPUT_ROOT from the environment
(env.sh).
"""
import json, os, re, sys

DRY_RUN = "--dry-run" in sys.argv

# The encoding the demo used before it moved to rt-media-origin (rt-mbs-examples'
# live-encoder.sh: -vf scale=960:540 -profile:v main -r 30, AAC 48 kHz at 64 kbit/s), carried over
# so that changing the origin does not also change the picture. No clause governs these: they are
# operator choices, and the bit rate is the one exposed in env.sh.
VIDEO_WIDTH, VIDEO_HEIGHT, VIDEO_PROFILE, VIDEO_FPS = 960, 540, "main", 30
AUDIO = {"bitrate": "64k", "sampleRate": 48000}

# rt-media-origin mounts a channel at its mountPath and channel ids must match this pattern
# (config/config.schema.json, definitions.channel.properties.id). The stream becomes a URL path
# segment, so it is held to the same character set.
SAFE_NAME = re.compile(r"^[a-zA-Z0-9_-]+$")


def origin_channel(c, env):
    """One rt-media-origin channel for one channels.json entry."""
    for key in ("id", "stream"):
        if not SAFE_NAME.match(c[key]):
            raise SystemExit(f"channel {c['id']!r}: {key} {c[key]!r} must match {SAFE_NAME.pattern}")
    source = os.path.join(env["CONTENT_ROOT"], c["source"])
    output = {
        "dir": os.path.join(env["ORIGIN_OUTPUT_ROOT"], c["stream"]),
        "format": "dash",
        "segDuration": float(env["LIVE_SEG_DURATION"]),
        "window": int(env["LIVE_WINDOW"]),
        "extraWindow": int(env["LIVE_EXTRA_WINDOW"]),
    }
    # A radio service is served as audio only, whatever the source carries: rt-media-origin's
    # audioOnly channel selects the source's audio and encodes no video, so it takes no ladder, fps
    # or video codec.
    if c.get("type") == "radio":
        return {
            "id": c["id"],
            "mode": "live",
            "audioOnly": True,
            "source": source,
            "mountPath": f"/{c['stream']}",
            "output": output,
            "audio": dict(AUDIO),
            "transport": "http",
        }
    return {
        "id": c["id"],
        "mode": "live",
        "source": source,
        "fps": VIDEO_FPS,
        "mountPath": f"/{c['stream']}",
        "output": dict(output, codec="h264"),
        # No label: rt-media-origin draws a rung's label into the picture, which the previous
        # encoder never did.
        "ladder": [{
            "width": VIDEO_WIDTH,
            "height": VIDEO_HEIGHT,
            "videoBitrate": env["LIVE_VIDEO_BITRATE"],
            "profile": VIDEO_PROFILE,
        }],
        "audio": dict(AUDIO),
        "transport": "http",
    }


def origin_config(channels, env):
    only = [x for x in env.get("DEMO_CHANNELS", "").replace(",", " ").split() if x]
    if only:
        channels = [c for c in channels if c["id"] in only]
    streams = [c["stream"] for c in channels]
    dupes = sorted({s for s in streams if streams.count(s) > 1})
    if dupes:
        raise SystemExit(f"channels.json: stream used by more than one channel: {', '.join(dupes)}")
    return {
        "server": {
            "port": int(env["MEDIA_PORT"]),
            "host": env["MEDIA_HOST"],
            # The receiver's page fetches manifests and segments straight from the origin, from
            # another origin (the client's), so the responses need CORS headers.
            "cors": True,
            "logLevel": "tiny",
        },
        "channels": [origin_channel(c, env) for c in channels],
    }


def main():
    env = os.environ
    with open(env["CHANNELS_FILE"]) as f:
        channels = json.load(f)["channels"]
    cfg = origin_config(channels, env)
    if DRY_RUN:
        print(json.dumps(cfg, indent=2))
        return
    out = env["ORIGIN_CONFIG"]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")
    print(f"  wrote {out}")
    for ch in cfg["channels"]:
        print(f"  {ch['id']:<12} {ch['mountPath']}/manifest.mpd  <-  {ch['source']}")


if __name__ == "__main__":
    main()
